name: coffee
description: App for coffee houses

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  built_value: ^6.1.4
  firebase_database: ^1.0.4
  firebase_storage: ^1.0.2
  firebase_auth: ^0.5.20
  scoped_model: ^0.3.0

dev_dependencies:
 # flutter_test:
 #   sdk: flutter
  build:
  build_runner:
  source_gen:
  built_value_generator:



flutter:
  uses-material-design: true

  assets:
    - assets/background_images/coffee.png
    - assets/product_images/americano.png

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Play
      fonts:
        - asset: fonts/Play-Bold.ttf
        - asset: fonts/Play-Regular.ttf