name: coffee
description: App for coffee houses

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/background_images/coffee.png
    - assets/product_images/americano.png

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf